version: '3.1'

services:

  mongo:
    image: mongo:7.0.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  listener:
    image: listener
    build: listener
    depends_on:
      - mongo

  tester:
    image: tester
    build: tester
    depends_on:
      - listener
